development:
  domain_name:       <%= ENV["DOMAIN_NAME"] %>
  secret_key_base:   <%= ENV["SECRET_KEY_BASE_DEVELOPMENT"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>

test:
  domain_name:       <%= ENV["DOMAIN_NAME"] %>
  secret_key_base:   <%= ENV["SECRET_KEY_BASE_TEST"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>

production:
  domain_name:       <%= ENV["DOMAIN_NAME"] %>
  secret_key_base:   <%= ENV["SECRET_KEY_BASE_PRODUCTION"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
